[DEFAULT]
compression = gz
debian-branch = debian/master
upstream-branch = upstream
pristine-tar = True

[pq]
patch-numbers = False

[dch]
id-length = 7

[import-orig]
# filter out unwanted files/dirs from upstream
filter = [
 '.envrc',
 '.tox',
 ]
# filter the files out of the tarball passed to pristine-tar
filter-pristine-tar = True
